import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from '../../components/navbar/navbar'
import AllSalesByMonth from '../../components/columnChart/allSalesByMonth'
import SalesProductMonthlyCategory from '../../components/lineChart/salesProductMonthlyCategory'
import SubCategorySales from '../../components/heatmap/subCategorySales'
import LastSales from '../../components/table/lastSales'

export default function Sales() {
  return (
    <>
        <Head>
            <title>CustomAnalytic</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Navbar active={"sales"}/>
          <div className='pt-4'>
            <div className='mt-5'>
              <div className={styles.container} style={{width:"100%", height:"90vh"}}>
                <SubCategorySales/>
              </div>
            </div>
            <div className='row mt-5'>
              <div className='col-lg-7 col-md-7 col-sm-12'>
                <div className={styles.container} style={{width:"100%", height:"50vh"}}>
                  <AllSalesByMonth/>
                </div>
                <div className={styles.container} style={{width:"100%", height:"60vh"}}>
                  <SalesProductMonthlyCategory/>
                </div>
              </div>
              <div className='col-lg-5 col-md-5 col-sm-12'>
                <div className={styles.container} style={{width:"100%"}}>
                  <LastSales/>
                </div>
              </div>
            </div>
          </div>
        </main>
    </>
  )
}
