import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from '../../components/navbar/navbar'
// import MostExpensive from '../components/donutChart/mostExpensive'

export default function Products() {
  return (
    <>
        <Head>
            <title>CustomAnalytic</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Navbar active={"products"}/>
            <div className='pt-3'>
                
            </div>
        </main>
    </>
  )
}
