import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from '../../components/navbar/navbar'
import MostColor from '../../components/donutChart/mostColor'
import MostSize from '../../components/donutChart/mostSize'

export default function Products() {
  return (
    <>
        <Head>
            <title>CustomAnalytic</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Navbar active={"products"}/>
            <div className='pt-4'>
              <div className='row mt-5'>
                <div className='col-lg-6 col-md-6 col-sm-12'>
                  <div className={styles.container} style={{width:"100%", height:"50vh"}}>
                    <MostColor/>
                  </div>
                </div>
                <div className='col-lg-6 col-md-6 col-sm-12'>
                  <div className={styles.container} style={{width:"100%", height:"50vh"}}>
                    <MostSize/>
                  </div>
                </div>
              </div>
            </div>
        </main>
    </>
  )
}
